services:
  # A Ktor web service
  - type: web
    name: crypto-daily
    runtime: docker
    repo: https://github.com/zac4j/crypto-daily.git
    branch: main
    plan: starter
    envVars:
    - key: MONGO_HOST
      fromService:
        name: mongodb
        type: pserv
        property: host
    - key: MONGO_PORT
      fromService:
        name: mongodb
        type: pserv
        property: port
  # MongoDB
  - type: pserv
    name: mongodb
    runtime: docker
    repo: https://github.com/zac4j/render-mongodb.git
    autoDeploy: false
    disk:
      name: mongodb-data
      mountPath: /data/db
      sizeGB: 10